name: Compile C++ Code

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: g++ -o my_executable.exe main.cpp
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my_executable
        path: my_executable.exe
